Dazure/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ressource/', include('ressource.urls')),
    url(r'^', include('ressource.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ressource/urls.py
from django.conf.urls import url
from . import views

app_name = 'ressource'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^(?P<ressource_id>[0-9]+)/$', views.detail, name='detail_ressource'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_ressource/$', views.create_ressource, name='create_ressource'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_ressource/$', views.delete_ressource, name='delete_ressource'),
    url(r'^(?P<ressource_id>[0-9]+)/create_storage/$', views.create_storage, name='create_storage'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_storage/(?P<storage_id>[0-9]+)/$', views.delete_storage, name='delete_storage'),
    url(r'^(?P<ressource_id>[0-9]+)/create_vnet/$', views.create_vnet, name='create_vnet'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_vnet/(?P<vnet_id>[0-9]+)/$', views.delete_vnet,name='delete_vnet'),
    url(r'^(?P<ressource_id>[0-9]+)/create_subnet/$', views.create_subnet, name='create_subnet'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_subnet/(?P<subnet_id>[0-9]+)/$', views.delete_subnet, name='delete_subnet'),
    url(r'^(?P<ressource_id>[0-9]+)/create_nic/$', views.create_nic, name='create_nic'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_nic/(?P<nic_id>[0-9]+)/$', views.delete_nic, name='delete_nic'),
    url(r'^(?P<ressource_id>[0-9]+)/create_virtualMachine/$', views.create_virtualMachine, name='create_virualMachine'),
    url(r'^(?P<ressource_id>[0-9]+)/delete_virtualMachine/(?P<virtualMachine_id>[0-9]+)/$', views.delete_virtualMachine, name='delete_virtualMachine'),
    url(r'^(?P<ressource_id>[0-9]+)/automation/(?P<operation_id>[0-9]+)/$', views.automation, name='automation')
    ]

ressource/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from docutils.parsers.rst.directives import choice

LOCATIONS=(
    ('westus','West US'),
    ('westus2','West US2'),
    ('centralus','Central US'),
    ('eastasia', 'East Asia'),
    ('southeastasia','South East Asia'),
    ('eastus','East US'),
    ('eastus2','East US2'),
    ('northcentralus','North Central US'),
    ('southcentralus','South Central US'),
    ('westcentralus','West Central US'),
    ('northeurope','North Europoe'),
    ('westeurope','West Europe'),
    ('japaneast','Japan EAST'),
    ('japanwest','Japan WEST'),
    ('brazilsouth','Brazil South'),
    ('australiasoutheast','Australia South East'),
    ('australiaeast','Australia EAST'),
    ('westindia','West India'),
    ('southindia','South India'),
    ('centralindia','Central India'),
    ('canadacentral','Canada Central'),
    ('canadaeast','Canada East'),
    ('uksouth','UK South'),
    ('ukwest','UK West'),
    ('koreacentral','Korea Central'),
    ('koreasouth','Korea South')
)
ADDRESS_PREFIXES=(
    ('10.0.0.0/10', '10.0.0.0/10'),
    ('10.0.0.0/11', '10.0.0.0/11'),
    ('10.0.0.0/12', '10.0.0.0/12'),
    ('10.0.0.0/13', '10.0.0.0/13'),
    ('10.0.0.0/14', '10.0.0.0/14'),
    ('10.0.0.0/15', '10.0.0.0/15'),
    ('10.0.0.0/16', '10.0.0.0/16'),
    ('192.168.1.0/16', '192.168.1.0/16'),
    ('192.168.1.0/17', '192.168.1.0/17'),
    ('192.168.1.0/18', '192.168.1.0/18'),
    ('192.168.1.0/19', '192.168.1.0/19'),
    ('192.168.1.0/20', '192.168.1.0/20'),
    ('172.16.1.0/10', '172.16.1.0/10'),
    ('172.16.1.0/11', '172.16.1.0/11'),
    ('172.16.1.0/12', '172.16.1.0/12'),
    ('172.16.1.0/13', '172.16.1.0/13'),
    ('172.16.1.0/14', '172.16.1.0/14'),
    ('172.16.1.0/15', '172.16.1.0/15'),
    ('172.16.1.0/16', '172.16.1.0/16'),
)

VM_REFERENCE=(
    ('linux','linux'),
    ('windows','windows')
)


class Ressources(models.Model):
    user = models.ForeignKey(User,default=1)
    groupe_name = models.CharField(max_length=250,verbose_name="Groupe name")
    location = models.CharField(max_length=250, choices=LOCATIONS,default='westus',verbose_name='Location')

    def __str__(self):
        return self.groupe_name

class Storages(models.Model):
    ressource = models.ForeignKey(Ressources)
    storage_account_name = models.CharField(max_length=250,verbose_name="Storage account name")

    def __str__(self):
        return self.storage_account_name

class Vnet(models.Model):
    ressource = models.ForeignKey(Ressources)
    vnet_name = models.CharField(max_length=250,verbose_name="Virtual network name")
    location = models.CharField(max_length=250,choices=LOCATIONS, default='westus',verbose_name="Location")
    address_prefixes = models.CharField(max_length=250,choices=ADDRESS_PREFIXES,default='10.0.0.0/16',verbose_name="Address prefixes")

    def __str__(self):
        return self.vnet_name

class Subnet(models.Model):
    ressource = models.ForeignKey(Ressources)
    vnet = models.ForeignKey(Vnet)
    subnet_name = models.CharField(max_length=250)
    address_prefixes = models.CharField(max_length=250, choices=ADDRESS_PREFIXES, default='10.0.0.0/16')

    def __str__(self):
        return self.subnet_name

class Nic(models.Model):
    ressource = models.ForeignKey(Ressources)
    nic_name = models.CharField(max_length=250)
    location = models.CharField(max_length=250,choices=LOCATIONS, default='westus')
    ip_configuration_name = models.CharField(max_length=250)
    subnet = models.ForeignKey(Subnet)
    vnet = models.ForeignKey(Vnet)

    def __str__(self):
        return self.nic_name

class UserCloud(models.Model):
    user = models.OneToOneField(User)
    username_azure = models.CharField(max_length=500)
    password_azure = models.CharField(max_length=500)
    subscription_id = models.CharField(max_length=500)
    client_id = models.CharField(max_length=500)
    secret = models.CharField(max_length=500)
    tenant = models.CharField(max_length=500)

    def __str__(self):
        return self.subscription_id

class VirtualMachine(models.Model):
    ressource = models.ForeignKey(Ressources)
    nic = models.ForeignKey(Nic)
    storage = models.ForeignKey(Storages)
    vm_name = models.CharField(max_length=250,verbose_name="Virtual Machine name")
    location = models.CharField(max_length=250,choices=LOCATIONS,default='10.0.0.0/16',verbose_name="Location")
    vm_reference = models.CharField(max_length=250,choices=VM_REFERENCE,default='linux',verbose_name='Operating System')
    os_disk_name = models.CharField(max_length=250,default='os_disk_name')

ressource/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import RessourcesForm,UserForm,StoragesForm,VnetForm,SubnetForm,NicForm,VirtualMachineForm
from .models import Ressources,User,UserCloud,Storages,Vnet,Subnet,Nic,VirtualMachine

from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.storage import StorageManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.compute import ComputeManagementClient
from haikunator import Haikunator
haikunator = Haikunator()


VM_REFERENCE = {
    'linux': {
        'publisher': 'Canonical',
        'offer': 'UbuntuServer',
        'sku': '16.04.0-LTS',
        'version': 'latest'
    },
    'windows': {
        'publisher': 'MicrosoftWindowsServerEssentials',
        'offer': 'WindowsServerEssentials',
        'sku': 'WindowsServerEssentials',
        'version': 'latest'
    }
}

def create_ressource(request):
    if not request.user.is_authenticated():
        return render(request, 'ressource/login.html')
    else:
        form = RessourcesForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            ressource = form.save(commit=False)
            ressource.user = request.user

            userCloud = get_object_or_404(UserCloud, user=(request.user))
            subscription_id = userCloud.subscription_id  # your Azure Subscription Id
            credentials = ServicePrincipalCredentials(
                client_id=userCloud.client_id,
                secret=userCloud.secret,
                tenant=userCloud.tenant
            )

            client = ResourceManagementClient(credentials, subscription_id)
            resource_group_params = {'location': form.cleaned_data['location']}
            print('Create Resource Group')
            client.resource_groups.create_or_update(form.cleaned_data['groupe_name'], resource_group_params)
            ressource.save()
            return render(request, 'ressource/detail_ressource.html', {'ressource': ressource})
        context = {
            "form": form,
        }
        return render(request, 'ressource/create_ressource.html', context)



def delete_ressource(request, ressource_id):
    ressource = Ressources.objects.get(pk=ressource_id)

    userCloud = get_object_or_404(UserCloud, user=(request.user))
    subscription_id = userCloud.subscription_id  # your Azure Subscription Id
    credentials = ServicePrincipalCredentials(
        client_id=userCloud.client_id,
        secret=userCloud.secret,
        tenant=userCloud.tenant
    )

    resource_client = ResourceManagementClient(credentials, subscription_id)
    delete_async_operation = resource_client.resource_groups.delete(ressource.groupe_name)
    delete_async_operation.wait()

    ressource.delete()
    ressource = Ressources.objects.filter(user=request.user)
    return render(request, 'ressource/index.html', {'ressources': ressource})




def create_virtualMachine(request, ressource_id):
    form = VirtualMachineForm(request.POST or None, request.FILES or None)
    ressource = get_object_or_404(Ressources, pk=ressource_id)
    if form.is_valid():
        ressource_vm = ressource.virtualmachine_set.all()
        for s in ressource_vm:
            if s.vm_name == form.cleaned_data.get("vm_name"):
                context = {
                    'ressource': ressource,
                    'form': form,
                    'error_message': 'You already added that Virtual Machine',
                }
                return render(request, 'ressource/create_virtualMachine.html', context)
        vm = form.save(commit=False)
        vm.ressource = ressource

        userCloud = get_object_or_404(UserCloud, user=(request.user))
        subscription_id = userCloud.subscription_id  # your Azure Subscription Id
        credentials = ServicePrincipalCredentials(
            client_id=userCloud.client_id,
            secret=userCloud.secret,
            tenant=userCloud.tenant
        )
        compute_client = ComputeManagementClient(credentials, subscription_id)
        network_client = NetworkManagementClient(credentials, subscription_id)

        #Get The nic ID
        nic = network_client.network_interfaces.get(vm.ressource.groupe_name,vm.nic.nic_name)


        print('\nCreating Virtual Machine')
        vm_parameters = create_vm_parameters(nic.id,VM_REFERENCE[vm.vm_reference],vm)
        async_vm_creation = compute_client.virtual_machines.create_or_update(
            vm.ressource.groupe_name, vm.vm_name, vm_parameters)
        async_vm_creation.wait()

        vm.save()
        return render(request, 'ressource/detail_ressource.html', {'ressource': ressource})
    context = {
        'ressource': ressource,
        'form': form,
    }
    return render(request, 'ressource/create_virtualMachine.html', context)

def delete_virtualMachine(request, ressource_id, virtualMachine_id):
    ressource = get_object_or_404(Ressources, pk=ressource_id)
    vm = VirtualMachine.objects.get(pk=virtualMachine_id)

    userCloud = get_object_or_404(UserCloud, user=(request.user))
    subscription_id = userCloud.subscription_id  # your Azure Subscription Id
    credentials = ServicePrincipalCredentials(
        client_id=userCloud.client_id,
        secret=userCloud.secret,
        tenant=userCloud.tenant
    )
    compute_client = ComputeManagementClient(credentials, subscription_id)
    network_client = NetworkManagementClient(credentials, subscription_id)

    async_vm_delete = compute_client.virtual_machines.delete(vm.ressource.groupe_name,vm.vm_name)
    async_vm_delete.wait()
    vm.delete()
    return render(request, 'ressource/detail_ressource.html', {'ressource': ressource})


def create_storage(request, ressource_id):
    print(ressource_id)
    form = StoragesForm(request.POST or None, request.FILES or None)
    ressource = get_object_or_404(Ressources, pk=ressource_id)
    if form.is_valid():
        ressource_storages = ressource.storages_set.all()
        for s in ressource_storages:
            if s.storage_account_name == form.cleaned_data.get("storage_account_name"):
                context = {
                    'ressource': ressource,
                    'form': form,
                    'error_message': 'You already added that storage',
                }
                return render(request, 'ressource/create_storage.html', context)
        storages = form.save(commit=False)
        storages.ressource = ressource

        userCloud = get_object_or_404(UserCloud, user=(request.user))
        subscription_id = userCloud.subscription_id  # your Azure Subscription Id
        credentials = ServicePrincipalCredentials(
            client_id=userCloud.client_id,
            secret=userCloud.secret,
            tenant=userCloud.tenant
        )
        storage_client = StorageManagementClient(credentials, subscription_id)
        storage_async_operation = storage_client.storage_accounts.create(
            storages.ressource.groupe_name,
            form.cleaned_data['storage_account_name'],
            {
                'sku': {'name': 'standard_lrs'},
                'kind': 'storage',
                'location': storages.ressource.location
            }
        )
        storage_async_operation.wait()


        storages.save()
        return render(request, 'ressource/detail_ressource.html', {'ressource': ressource})
    context = {
        'ressource': ressource,
        'form': form,
    }
    return render(request, 'ressource/create_storage.html', context)

def delete_storage(request, ressource_id, storage_id):
    ressource = get_object_or_404(Ressources, pk=ressource_id)
    storage = Storages.objects.get(pk=storage_id)

    userCloud = get_object_or_404(UserCloud, user=(request.user))
    subscription_id = userCloud.subscription_id  # your Azure Subscription Id
    credentials = ServicePrincipalCredentials(
        client_id=userCloud.client_id,
        secret=userCloud.secret,
        tenant=userCloud.tenant
    )
    storage_client = StorageManagementClient(credentials, subscription_id)
    storage_client.storage_accounts.delete(storage.ressource.groupe_name,storage.storage_account_name)
    storage.delete()
    return render(request, 'ressource/detail_ressource.html', {'ressource': ressource})


def create_subnet(request, ressource_id):
    print(ressource_id)
    form = SubnetForm(request.POST or None, request.FILES or None)
    ressource = get_object_or_404(Ressources, pk=ressource_id)
    if form.is_valid():
        ressource_subnets = ressource.subnet_set.all()
        for s in ressource_subnets:
            if s.subnet_name == form.cleaned_data.get("subnet_name"):
                context = {
                    'ressource': ressource,
                    'form': form,
                    'error_message': 'You already added that subnet',
                }
                return render(request, 'ressource/create_subnet.html', context)
        subnet = form.save(commit=False)
        subnet.ressource = ressource

        userCloud = get_object_or_404(UserCloud, user=(request.user))
        subscription_id = userCloud.subscription_id  # your Azure Subscription Id
        credentials = ServicePrincipalCredentials(
            client_id=userCloud.client_id,
            secret=userCloud.secret,
            tenant=userCloud.tenant
        )
        network_client = NetworkManagementClient(credentials, subscription_id)

        async_subnet_creation = network_client.subnets.create_or_update(
            subnet.ressource.groupe_name,
            subnet.vnet.vnet_name,
            form.cleaned_data['subnet_name'],
            {'address_prefix': form.cleaned_data['address_prefixes']}
        )
        async_subnet_creation.wait()
        subnet.save()

ressource/templates/ressource/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dazure{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'ressource/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'ressource/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ressource:index' %}">Dazure</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'ressource:index' %}">Ressources</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'ressource:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'ressource:create_ressource' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Ressource
                    </a>
                </li>
                <li>
                    <a href="{% url 'ressource:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ressource/templates/ressource/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dazure{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'ressource/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'ressource/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ressource:index' %}">Dazure</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'ressource:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'ressource:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ressource/templates/ressource/detail_ressource.html
{% extends 'ressource/base.html' %}
{% block title %}{{ ressource }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'ressource:detail_ressource' ressource.id %}">
                            <img src="/media/ressource.png" class="img-responsive">
                        </a>
                    <h4><b>Ressource name :</b> {{ ressource.groupe_name }} </h4>
                    <h4><b>Ressource location :</b> {{ ressource.location }} </h4>
                    <h4><b>State :</b> Active </h4>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'ressource:detail_ressource' ressource.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'ressource:create_storage' ressource.id %}">Storage account</a></li>
                <li role="presentation"><a href="{% url 'ressource:create_vnet' ressource.id %}">Virtual Network</a></li>
                <li role="presentation"><a href="{% url 'ressource:create_subnet' ressource.id %}">Network Subnet</a></li>
                <li role="presentation"><a href="{% url 'ressource:create_nic' ressource.id %}">Network Interface</a></li>
                <li role="presentation"><a href="{% url 'ressource:create_virualMachine' ressource.id %}">Virtual Machines</a></li>
                <li role="presentation"><a href="{% url 'ressource:automation' ressource.id 0 %}">Automations</a></li>


            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All ressources</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
<table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                           {% for storage in ressource.storages_set.all %}
                            <tr>
                                <td>{{ storage.storage_account_name }}</td>
                                <td>Storage account</td>
                            <td>
                                    <form action="{% url 'ressource:delete_storage' ressource.id storage.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="storage_id" value="{{ storage.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                            {% for vnet in ressource.vnet_set.all %}
                            <tr>
                                <td>{{ vnet.vnet_name }}</td>
                                <td>Virtual Network</td>
                            <td>
                                    <form action="{% url 'ressource:delete_vnet' ressource.id vnet.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="vnet_id" value="{{ vnet.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        {% for subnet in ressource.subnet_set.all %}
                            <tr>
                                <td>{{ subnet.subnet_name }}</td>
                                <td>Network Subnet</td>
                             <td>
                                    <form action="{% url 'ressource:delete_subnet' ressource.id subnet.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="subnet_id" value="{{ subnet.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                         {% for nic in ressource.nic_set.all %}
                            <tr>
                                <td>{{ nic.nic_name }}</td>
                                <td>Network Interface</td>
                             <td>
                                    <form action="{% url 'ressource:delete_nic' ressource.id nic.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="nic_id" value="{{ nic.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        {% for vm in ressource.virtualmachine_set.all %}
                            <tr>
                                <td>{{ vm.vm_name }}</td>
                                <td>Virtual Machine</td>
                             <td>
                                    <form action="{% url 'ressource:delete_virtualMachine' ressource.id vm.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="nic_id" value="{{ vm.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>


                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

ressource/templates/ressource/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ressource/templates/ressource/index.html
{% extends 'ressource/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Ressources</h3>
        </div>
        {% if ressources %}
            {% for ressource in ressources %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                         <a href="{% url 'ressource:detail_ressource' ressource.id %}">
                            <img src="/media/ressource.png" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h4>{{ ressource.groupe_name }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'ressource:detail_ressource' ressource.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Ressource -->
                            <form action="{% url 'ressource:delete_ressource' ressource.id  %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="ressource_id" value="{{ ressource.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'ressource:create_ressource' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Ajouter une ressource
                    </button>
                </a>
            </div>
        {% endif %}
    </div>


</div>
{% endblock %}